# Generated by Django 3.0.8 on 2020-07-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200712_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closedbid',
            name='description',
        ),
        migrations.RemoveField(
            model_name='closedbid',
            name='link',
        ),
        migrations.RemoveField(
            model_name='closedbid',
            name='time',
        ),
        migrations.RemoveField(
            model_name='closedbid',
            name='titl',
        ),
    ]
